import Signup from "@/components/signup";
import Head from "next/head";

// Página de SignUp con el componente signup para crear una nueva cuenta en el sistema
export default function signUpPage() {
	return (
		<>
			<Head>
				<title>InvitApp</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Signup></Signup>
			</main>
		</>
	);
}
